apiVersion: batch/v1          # 👈 1. 更新為正式穩定版 API
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: alpine     # 👈 2. 修正映像檔拼字 (apline -> alpine)
            args:
            - /bin/sh
            - -c
            - echo "Hi, current time is $(date)"
          restartPolicy: OnFailure