apiVersion: apps/v1 # for kubectl versions >= 1.9.0 use apps/v1
kind: Deployment
metadata:
  name: current-chipmunk-deployment #这个根据题目要求修改
  namespace: goshawk
spec:
  replicas: 6
  selector:
    matchLabels:
      app: current-chipmunk-deployment #作为区分标签
      run: dep-svc #确保 current-chipmunk-deployment 和 canary-chipmunk-deployment 都有这个公用的标签。
  template:
    metadata:
      labels:
        app: current-chipmunk-deployment
        run: dep-svc
    spec:
      containers:
      - name: nginx
        image: vicuu/nginx:hi
        ports:
        - containerPort: 3000