apiVersion: v1
kind: Secret
metadata:
  name: another-secret
  namespace: default
type: Opaque
stringData:
  key1: value12
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:1.16
    env:
    - name: COOL_VARIABLE
      valueFrom: 
        secretKeyRef:
          name: another-secret
          key: key1
