apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: haddock
spec:
  limits:
  - type: Container
    max:
      memory: 40Mi
    defaultRequest:
      memory: 8Mi
    default:
      memory: 16Mi