apiVersion: v1
kind: Service
metadata:
  name: wordpress-service-diff
spec:
  ports:
  - port: 3000
    nodePort: 30301
    protocol: TCP
    targetPort: wordpress-port
  selector:
    app: wordpress
  type: NodePort