apiVersion: v1
kind: Secret
metadata:
  name: wordpress-stateful-secret
type: Opaque
data:
  # echo -n "wordpressRoot123" | base64
  db-password: d29yZHByZXNzUm9vdDEyMw==
  # 以下 8 組皆為 openssl rand -base64 48 產生後再 base64 編碼，供 WordPress 加密 cookie / session 使用
  auth_key: MVhVSFUvczhMdThDY0JjNGlrd2Jrcitvb2paKzM0UWVqVVBWWW42VThXbnYvOVJNeHZla01CdklQSkVOTjFudw==
  auth_salt: QVpzYU1jZExiVVFFNUo4Q1ZxeDgzQlpMZXNQMUJPMTRURHdSVVFxMTh0UWIyMStVYVljT1FUNlZPdVZQd0tDWQ==
  secure_auth_key: bVVqZmJVWFRabDZ3bVRlbEpNWTNzTnczV3VQMGdmbmxRZTJkNWJhV052OWRSWnhINlRwUGs3THhBWFhxck9ucA==
  secure_auth_salt: bG1jbXZ0RVpBajhESUgrcm8rM1FjRTlLbTdhYU5IR0NaMjU2b3J1T203bEt0Z0Zkd0Uya1VrRm1BMzRoa3hyRA==
  logged_in_key: ZkZSTWtab2ZsTHZjRXJ3dWlFdkROaEw5SWtNbGpwVWM3ZFpOQXFOTklDcW9NVlFlZWYvSmx5L09lanNxMGI4ZQ==
  logged_in_salt: d1BGQTVhMTJDbm52K1FtL0JQRlQ2SjQ3VE5VdzJNMTQ1RlgzVjdlRnFQMnFoNm4yczUxZjJvanliUFdwd3B3Vg==
  nonce_key: SGdqRzEzUGxnMzJIeW1SYkZJTnEwTFkxbi9HWlFqdkFQTmtHbVdWams1K3doUlFJTjhDVnFycVZHcXp4UDJUZg==
  nonce_salt: ODFmR1RrMCtHd095R1FNS1NDZkk5VlUzVDZTT3JHKzFXbGtpV1luc2ZSZ0QxeXRCREpBUFBmNHdRTmZEa3N1Qw==
