apiVersion: v1
kind: Service
metadata:
  name: wordpress-stateful-service
spec:
  ports:
  - port: 3000
    nodePort: 30302
    protocol: TCP
    targetPort: wordpress-port
  selector:
    app: wordpress-stateful
  type: NodePort
